// Master glossary: difficult English words → isiZulu translations
// Used by GlossaryText component for hover tooltips
// ~2000 terms covering business, innovation, finance, technology, education, and general vocabulary

const GLOSSARY = {
  // ═══════════════════════════════════════════════════════════════════════════
  // BUSINESS & ENTREPRENEURSHIP
  // ═══════════════════════════════════════════════════════════════════════════
  "opportunit": "ithuba",
  "entrepreneur": "usomabhizinisi",
  "venture": "ibhizinisi elisha",
  "startup": "ibhizinisi elisha",
  "enterprise": "ibhizinisi",
  "corporation": "inkampani enkulu",
  "conglomerat": "iqoqo lezinkampani",
  "subsidiary": "inkampani engaphansi",
  "headquarter": "ihhovisi elikhulu",
  "franchis": "ilungelo lokusebenzisa igama",
  "partnership": "ubambiswano",
  "sole proprietor": "umnikazi oyedwa",
  "joint venture": "ibhizinisi elihlanganyelwayo",
  "merger": "ukuhlanganiswa kwezinkampani",
  "acquisition": "ukuthenga inkampani",
  "takeover": "ukuthatha inkampani",
  "incorporat": "ukubhaliswa kwenkampani",
  "stakeholder": "umuntu onentshisekelo",
  "shareholder": "umnikazi wamasheya",
  "board of director": "ibhodi labaqondisi",
  "chief executive": "isikhulu esiphezulu",
  "managemen": "ukuphatha",
  "operation": "ukusebenza",
  "administrat": "ukuphatha",
  "bureaucrac": "ubuhlakani bokubusa",
  "hierarch": "izigaba zamandla",
  "organiz": "ukuhlela",
  "restructur": "ukwakha kabusha",
  "downsiz": "ukunciphisa abasebenzi",
  "outsourc": "ukuqasha ngaphandle",
  "supply chain": "umkhiqizo wokuphakela",
  "vendor": "umthengisi",
  "supplier": "umhlinzeki",
  "wholesal": "ukuthengisa ngobuningi",
  "retail": "ukuthengisela abantu",
  "distributor": "umabeli",
  "manufactur": "ukukhiqiza",
  "productio": "ukukhiqiza",
  "assembl": "ukuhlanganisa",
  "fabricat": "ukwenza",
  "warehousing": "ukugcina izimpahla",
  "inventor": "izimpahla ezigciniwe",
  "logistic": "ukuhambisa izimpahla",
  "procurement": "ukuthenga izimpahla",
  "tender": "isicelo sokuthenga",
  "contract": "isivumelwano",
  "agreement": "isivumelwano",
  "negotiat": "ukuxoxisana",
  "arbitrat": "ukulamula",
  "mediat": "ukuxazulula",
  "litigat": "ukumangalela",
  "complianc": "ukulandela imithetho",
  "regulat": "imithetho",
  "legislat": "umthetho",
  "jurisdict": "indawo yomthetho",
  "liability": "isikweletu",
  "indemnit": "isinxephezelo",
  "warrant": "isiqinisekiso",
  "disclaim": "ukuphika",
  "proprietar": "okungokwakho",
  "intellectual property": "impahla yomqondo",
  "patent": "ilungelo lokusungula",
  "trademark": "uphawu lohwebo",
  "copyright": "ilungelo lobunikazi",
  "licensing": "ukunikeza ilayisensi",
  "royalt": "imali yokusetshenziswa",

  // ═══════════════════════════════════════════════════════════════════════════
  // FINANCE & ACCOUNTING
  // ═══════════════════════════════════════════════════════════════════════════
  "investment": "ukutshalwa kwezimali",
  "revenue": "imali engenayo",
  "profit": "inzuzo",
  "capital": "imali yokuqala",
  "budget": "isabelomali",
  "expenditur": "izindleko",
  "overhead": "izindleko zokusebenza",
  "turnover": "imali engenayo yonke",
  "earning": "imali eyenziwayo",
  "income": "imali engenayo",
  "gross": "inani elingakancishiswanga",
  "net": "inani elikhishiwe izindleko",
  "margin": "inzuzo ehlanzekile",
  "breakeven": "ukufinyelela ekungenanzuzini",
  "solven": "ukukwazi ukukhokha izikweletu",
  "insolven": "ukungakwazi ukukhokha",
  "liquidit": "ukutholakala kwemali",
  "asset": "impahla enani",
  "equit": "isabelo senkampani",
  "debt": "isikweletu",
  "loan": "isikweletu",
  "credit": "ukukweleta",
  "debit": "ukukhokha",
  "interest": "inzalo",
  "mortgage": "isibambiso sendlu",
  "collateral": "isibambiso",
  "dividend": "inzuzo eyabelwayo",
  "bond": "ibhondi",
  "securit": "izibambiso",
  "stock": "amasheya",
  "portfolio": "iqoqo lezimali",
  "diversif": "ukwandisa izinhlobo",
  "hedge": "ukuvikela izimali",
  "speculate": "ukuqagela ngezimali",
  "volatil": "ukuguquguquka kwezimali",
  "inflation": "ukwenyuka kwamanani",
  "deflation": "ukwehla kwamanani",
  "recession": "ukwehla komnotho",
  "depress": "ukwehla okukhulu komnotho",
  "stagnation": "ukungakhuli komnotho",
  "depreciat": "ukuncipha kwenani",
  "appreciat": "ukukhula kwenani",
  "amortizat": "ukukhokha kancane kancane",
  "bookkeeping": "ukugcina amarekhodi ezimali",
  "audit": "ukuhlolwa kwezimali",
  "invoice": "i-invoyisi",
  "receipt": "irisidi",
  "ledger": "ibhuku lezimali",
  "balance sheet": "ishidi lokulinganisa",
  "income statement": "umbiko wemali engenayo",
  "cash flow": "ukuhamba kwemali",
  "forecast": "ukubikezela",
  "tax": "intela",
  "tariff": "intela yokungenisa",
  "subsid": "usizo lwemali kahulumeni",
  "grant": "uxhaso lwemali",
  "endowment": "isipho semali",
  "philanthrop": "ukupha abanye",
  "fiduciar": "umphathi wezimali",
  "escrow": "imali egcinwe umlamuli",
  "disbursement": "ukukhokha imali",
  "reimbursement": "ukubuyiselwa imali",
  "remittance": "ukuthumela imali",
  "transact": "ukwenza imali",
  "forex": "ukushintsha imali yamanye amazwe",
  "currenc": "uhlobo lwemali",
  "exchange rate": "inani lokushintsha imali",
  "commodit": "izimpahla ezithengiswa",
  "futures": "izivumelwano zesikhathi esizayo",
  "derivativ": "izinto ezisukela kwezinye",
  "leverage": "ukusebenzisa isikweletu",
  "solvenc": "ukukwazi ukukhokha",
  "accountab": "ukuziphendulela",
  "transparen": "ukuba sobala",
  "fiscal": "ngezimali",
  "monetary": "ngemali",
  "microfinanc": "imali encane ebolekiswa",
  "crowdfund": "ukuqoqa imali kubantu abaningi",
  "venture capital": "imali yokutshala emabhizinisini amasha",
  "angel investor": "umtshalimali wokuqala",
  "initial public offering": "ukuthengisa amasheya okokuqala",
  "valuation": "ukuhlonza inani",
  "due diligenc": "ukuhlola ngokucophelela",

  // ═══════════════════════════════════════════════════════════════════════════
  // MARKETING & SALES
  // ═══════════════════════════════════════════════════════════════════════════
  "market size": "ubukhulu bemakethe",
  "market share": "isabelo semakethe",
  "target market": "imakethe ehlosiwe",
  "competitor": "umbangi",
  "competiti": "ukuncintisana",
  "customer": "ikhasimende",
  "consumer": "umsebenzisi",
  "clientele": "amakhasimende",
  "demographic": "iqembu labantu",
  "segmentat": "ukuhlukanisa imakethe",
  "niche": "indawo ekhethekile emakethe",
  "brand": "igama lomkhiqizo",
  "reputat": "igama elihle",
  "advertis": "ukukhangisa",
  "promot": "ukukhuthaza",
  "campaign": "umkhankaso",
  "engagemen": "ukuxhumana",
  "convers": "ukuguqulwa kwekhasimende",
  "retent": "ukugcina amakhasimende",
  "loyalt": "ukwethembeka",
  "satisfact": "ukwaneliseka",
  "testimonial": "ubufakazi bekhasimende",
  "referral": "ukudluliselwa",
  "affliat": "ubudlelwano bezinkampani",
  "sponsor": "umxhasi",
  "endorsement": "ukusekelwa",
  "influenc": "umthelela",
  "outreach": "ukufinyelela abantu",
  "pipeline": "uhlelo lwamakhasimende",
  "funnel": "isakhiwo sokuthengisa",
  "prospect": "ikhasimende elingaba",
  "lead": "ikhasimende elingaba",
  "cold call": "ukushayela umuntu ongamaziyo",
  "pitch": "ukwethula umqondo",
  "proposal": "isiphakamiso",
  "quotation": "intengo ephakanyisiwe",
  "discount": "isaphulelo",
  "incentiv": "isikhuthazi",
  "commission": "ikhomishini",
  "rebate": "imali ebuyiswayo",
  "premium": "inani eliphezulu",
  "commodity": "impahla ethengiswa",
  "benchmark": "amazinga okusebenza",

  // ═══════════════════════════════════════════════════════════════════════════
  // INNOVATION & TECHNOLOGY
  // ═══════════════════════════════════════════════════════════════════════════
  "innovat": "ukusungula",
  "disrupt": "ukuphazamisa imakethe",
  "prototype": "isibonelo sokuqala",
  "iteration": "ukuphinda ukwenza",
  "pivot": "ukushintsha indlela",
  "scalab": "okungakhuliswa",
  "agile": "ukusebenza ngokushesha",
  "lean": "ukusebenza ngokuonga",
  "minimum viable product": "umkhiqizo omncane osebenzayo",
  "mvp": "umkhiqizo omncane osebenzayo",
  "proof of concept": "ubufakazi bokuthi kuyasebenza",
  "incubator": "indawo yokufukamela ibhizinisi",
  "accelerator": "uhlelo lokusheshisa ukukhula",
  "ecosystem": "indawo yokusebenzisana",
  "platform": "ipulatifomu",
  "algorithm": "indlela yokubala",
  "artificial intelligence": "ubuhlakani bokwenziwa",
  "machine learning": "ukufunda komshini",
  "automation": "ukwenza ngokuzenzakalelayo",
  "blockchain": "uhlelo lokugcina idatha",
  "cryptocurrenc": "imali yedijithali",
  "cybersecurit": "ukuphepha ku-inthanethi",
  "cloud computing": "ukukhompyutha ngamafu",
  "big data": "idatha enkulu",
  "analytic": "ukuhlaziya idatha",
  "internet of things": "i-inthanethi yezinto",
  "virtual realit": "isimo esingokoqobo bokwenziwa",
  "augmented realit": "isimo sokoqobo esandisiwe",
  "bandwidth": "isikhala sedatha",
  "infrastructur": "ingqalasizinda",
  "e-commerce": "ukuthengisa ku-inthanethi",
  "digital": "okwedijithali",
  "software": "isofrithiwe",
  "hardware": "ihardwe",
  "firmware": "ifemwe",
  "interface": "indawo yokuxhumana",
  "database": "idathabeyisi",
  "server": "iseva",
  "network": "inethiwekhi",
  "protocol": "indlela yokuxhumana",
  "encrypt": "ukufihla idatha",
  "authenticat": "ukuqinisekisa ubunikazi",
  "biometric": "ukuqinisekisa ngomzimba",
  "firewall": "udonga lokuvikela",
  "malware": "isofrithiwe ebulalayo",
  "phishing": "ukukhohlisa nge-imeyili",
  "ransomware": "isofrithiwe efuna imali",
  "vulnerabilit": "ubuthakathaka",
  "patch": "ukulungisa",
  "deploy": "ukusebenzisa",
  "debug": "ukuqeda amaphutha",
  "compile": "ukuhlanganisa ikhodi",
  "repository": "indawo yokugcina ikhodi",
  "open source": "ikhodi evulelwe wonke umuntu",
  "proprietary": "ikhodi engeyomnikazi",
  "api": "indlela yokuxhumana namanye amasistimu",
  "saas": "isofrithiwe ebolekiswayo",
  "fintech": "ubuchwepheshe bezimali",
  "edtech": "ubuchwepheshe bezemfundo",
  "healthtech": "ubuchwepheshe lwezempilo",
  "agritech": "ubuchwepheshe bezolimo",
  "biotech": "ubuchwepheshe bezempilo yesayensi",
  "cleantech": "ubuchwepheshe obuhlanzekile",
  "deeptech": "ubuchwepheshe obujulile",
  "robotics": "isayensi yamarobhothi",
  "nanotechnolog": "ubuchwepheshe obuncane kakhulu",
  "3d printing": "ukuphrinta kwezinhlangothi ezintathu",
  "drone": "indiza engenaashayeli",
  "autonomous": "okuzisebenzayo",
  "sensor": "isiqaphi",
  "wearable": "okugqokwayo",
  "geolocation": "indawo yomhlaba",
  "telemedicin": "ukwelapha ngezingcingo",
  "tele-health": "ukwelapha kude",

  // ═══════════════════════════════════════════════════════════════════════════
  // STRATEGY & MANAGEMENT
  // ═══════════════════════════════════════════════════════════════════════════
  "strateg": "isu",
  "tactic": "indlela",
  "objective": "inhloso",
  "milestone": "isigaba esibalulekile",
  "roadmap": "uhlelo lwendlela",
  "kpi": "isilinganiso sokusebenza",
  "metric": "isilinganiso",
  "roi": "inzuzo ebuyelayo",
  "swot": "ukuhlaziya amandla nobuthakathaka",
  "feasibilit": "ukuhlolwa kokwenzeka",
  "viabilit": "ukuhlolwa kokusebenza",
  "sustainabilit": "ukuqhubekela phambili",
  "competitiv": "ukuncintisana",
  "differenti": "ukuzehlukanisa",
  "value proposition": "inani olithembisayo",
  "unique selling point": "into ekwenza uhluke",
  "core competenc": "amakhono ayisisekelo",
  "best practice": "izindlela ezinhle kakhulu",
  "synerg": "ukusebenzisana",
  "collaborat": "ukubambisana",
  "consolidat": "ukuhlanganisa",
  "streamlin": "ukwenza kube lula",
  "optimiz": "ukwenza kangcono",
  "implement": "ukwenza",
  "execut": "ukufeza",
  "delegat": "ukuphathisa",
  "empower": "ukunika amandla",
  "mentor": "umqeqeshi",
  "coach": "umqeqeshi",
  "facilitat": "ukusiza",
  "prioritiz": "ukubeka kuqala",
  "contingenc": "isicelo sezimo ezingalindelekile",
  "mitigat": "ukunciphisa ingozi",
  "risk management": "ukuphatha ingozi",
  "crisis management": "ukuphatha izimo ezinzima",
  "change management": "ukuphatha ushintsho",
  "project management": "ukuphatha iphrojekthi",
  "agile methodology": "indlela yokusebenza ngokushesha",
  "scrum": "indlela yokusebenza ngamaqembu",
  "kanban": "indlela yokubona umsebenzi",
  "lean startup": "ukuqala ibhizinisi ngokuonga",
  "design thinking": "ukucabanga ngendlela yokwakha",
  "business model canvas": "isakhiwo sebhizinisi",
  "pivot strateg": "ukushintsha isu",
  "exit strateg": "isu lokushiya",
  "succession plan": "uhlelo lokulandela",
  "contingency plan": "uhlelo lwezimo ezingalindelekile",
  "scenario plan": "uhlelo lwezimo ezahlukene",

  // ═══════════════════════════════════════════════════════════════════════════
  // HUMAN RESOURCES & WORKFORCE
  // ═══════════════════════════════════════════════════════════════════════════
  "recruitment": "ukuqasha",
  "onboard": "ukwamukela emsebenzini",
  "retention": "ukugcina abasebenzi",
  "attrition": "ukuhamba kwabasebenzi",
  "compensation": "ukukhokhelwa",
  "remunerati": "ukukhokhelwa",
  "salary": "iholo",
  "wage": "iholo",
  "benefit": "inzuzo",
  "pension": "impesheni",
  "retirement": "ukuthatha umhlalaphansi",
  "welfare": "inhlalakahle",
  "occupational": "ngomsebenzi",
  "ergonomic": "ukuphepha emsebenzini",
  "grievanc": "isikhalo",
  "disciplin": "isijeziso",
  "terminat": "ukuqeda umsebenzi",
  "redundanc": "ukuba ngaphezulu kwesidingo",
  "furlough": "ukuphumula okwesikhashana",
  "probation": "isikhathi sokuhlolwa",
  "apprenticeship": "ukuqeqeshwa emsebenzini",
  "internship": "ukuzijwayeza emsebenzini",
  "freelanc": "ukuzisebenzela",
  "gig economy": "umnotho wemisebenzi emifushane",
  "remote work": "ukusebenza kude",
  "hybrid work": "ukusebenza kuxutshiwe",
  "productivit": "ukukhiqiza",
  "performanc": "ukusebenza",
  "appraisal": "ukuhlolwa kokusebenza",
  "promotion": "ukukhushulwa",
  "demotion": "ukwehliswa",
  "seniority": "ubufana",
  "turnover rate": "izinga lokuhamba kwabasebenzi",

  // ═══════════════════════════════════════════════════════════════════════════
  // ECONOMICS & TRADE
  // ═══════════════════════════════════════════════════════════════════════════
  "econom": "umnotho",
  "macroeconomic": "umnotho omkhulu",
  "microeconomic": "umnotho omncane",
  "gdp": "umkhiqizo wezwe",
  "gnp": "umkhiqizo wezwe esizwe",
  "per capita": "ngomuntu ngamunye",
  "purchas": "ukuthenga",
  "procurement": "ukuthenga",
  "supply": "ukuhlinzeka",
  "demand": "isidingo",
  "equilibrium": "ukuhlangana kwentengo",
  "elasticit": "ukuguquguquka",
  "scarcit": "ukungatholakali",
  "abundanc": "ukuba ningi",
  "monopol": "ukubusa imakethe",
  "oligopol": "ukubuswa imakethe ngabambalwa",
  "cartel": "iqembu lezinkampani ezivumelene",
  "antitrust": "ukuvimbela ukubuswa kwemakethe",
  "deregulat": "ukususa imithetho",
  "privatiz": "ukwenza kube okwabazimele",
  "nationaliz": "ukwenza kube okukahulumeni",
  "austerit": "ukunqaba kwezimali",
  "stimulus": "isikhuthazi somnotho",
  "sanction": "isijeziso sezomnotho",
  "embargo": "ukuvinjelwa kohwebo",
  "trade deficit": "ukulahleka kwentela",
  "trade surplus": "inzuzo yohwebo",
  "import": "ukuthenga kwamanye amazwe",
  "export": "ukuthengisela amazwe",
  "bilateral": "phakathi kwamazwe amabili",
  "multilateral": "phakathi kwamazwe amaningi",
  "globalizat": "ukwanda emhlabeni wonke",
  "liberaliz": "ukukhulula imakethe",
  "protectionism": "ukuvikela imakethe yakho",
  "quota": "inani elivunyelwe",
  "infrastructur": "ingqalasizinda",
  "industrializ": "ukufaka izimboni",
  "urbaniz": "ukwanda kwamadolobha",
  "gentrific": "ukwakhiwa kabusha kwezindawo",
  "displacement": "ukususwa kwabantu",
  "remittanc": "ukuthumela imali",
  "diaspora": "abantu abahlala kude nekubo",
  "sovereignt": "ukuzibusa",
  "autonomous": "okuzibusayo",
  "federalism": "uhlelo lukahulumeni",
  "democrac": "intando yabantu",

  // ═══════════════════════════════════════════════════════════════════════════
  // EDUCATION & SKILLS
  // ═══════════════════════════════════════════════════════════════════════════
  "curriculum": "uhlelo lokufunda",
  "syllabus": "isifundo esibekiwe",
  "assessment": "ukuhlolwa",
  "evaluation": "ukuhlola",
  "accreditat": "ukuvunywa",
  "certificat": "isitifiketi",
  "diploma": "idiploma",
  "degree": "iziqu",
  "postgraduat": "izifundo ezilandela iziqu",
  "undergraduate": "izifundo zokuqala",
  "scholarship": "umfundaze",
  "bursary": "umfundaze",
  "tuition": "imali yokufunda",
  "enrollmen": "ukubhalisa",
  "matric": "imatriki",
  "literac": "ukufunda nokubhala",
  "numerac": "ukubala",
  "competenc": "ikhono",
  "proficienc": "ubungoti",
  "aptitude": "ikhono lemvelo",
  "pedagog": "indlela yokufundisa",
  "didactic": "okwemfundiso",
  "experiential": "ngokuzwa",
  "vocational": "ngomsebenzi",
  "technical": "ngobuchwepheshe",
  "tertiar": "imfundo ephakeme",
  "tvet": "imfundo noqeqesho lwezobuciko",
  "seta": "umkhandlu wemfundo noqeqesho",
  "learnershp": "uhlelo lokufundiswa",
  "mentorship": "ukuqeqeshwa",
  "workshop": "indawo yokufundela",
  "seminar": "isifundo esikhethekile",
  "symposium": "umhlangano wezifundiswa",
  "conference": "ingqungquthela",
  "webinar": "isifundo se-inthanethi",
  "e-learning": "ukufunda nge-inthanethi",
  "blended learning": "ukufunda okuxutshiwe",
  "distance learning": "ukufunda kude",
  "self-paced": "ukufunda ngejubane lakho",
  "cognitive": "ngokucabanga",
  "critical thinking": "ukucabanga okubanzi",
  "problem solving": "ukuxazulula izinkinga",
  "analytical": "okuhlaziyayo",
  "comprehens": "ukuqonda",
  "collaborat": "ukusebenzisana",
  "teamwork": "ukusebenza ndawonye",
  "leadership": "ubuholi",
  "communicat": "ukuxhumana",
  "presentat": "ukwethula",
  "articulat": "ukuchaza kahle",
  "eloquen": "ukukhuluma kahle",
  "persuasi": "ukuqoqa",
  "rhetor": "ubuchule bokukhuluma",
  "empathy": "ukuzwelana",
  "emotional intelligence": "ukuqonda imizwa",
  "resilience": "ukuqina",
  "perseveranc": "ukuphikelela",
  "tenacit": "ukubekezela",
  "diligen": "ukukhuthala",
  "disciplin": "ukuzithiba",
  "accountabilit": "ukuziphendulela",
  "integrity": "ubuqotho",
  "ethic": "okuhle nokubi",

  // ═══════════════════════════════════════════════════════════════════════════
  // SUSTAINABILITY & ENVIRONMENT
  // ═══════════════════════════════════════════════════════════════════════════
  "sustainab": "ukuqhubekela phambili",
  "renewable": "okuvuselelekayo",
  "non-renewable": "okungavuseleleki",
  "carbon footprint": "umthelela wekhabhoni",
  "emission": "ukuphuma kwegesi",
  "greenhouse": "ukushisa komhlaba",
  "climate change": "ukuguquka kwesimo sezulu",
  "biodiversit": "izinhlobo zempilo",
  "conservat": "ukongiwa kwemvelo",
  "ecosystem": "uhlelo lwemvelo",
  "deforestation": "ukugundwa kwamahlathi",
  "desertification": "ukwanda kwezindawo ezomile",
  "erosion": "ukukhukuliswa komhlabathi",
  "pollut": "ukungcola",
  "contaminat": "ukungcolisa",
  "remediat": "ukulungisa",
  "reclamation": "ukubuyisela esimweni",
  "recycl": "ukuphinda ukusebenzisa",
  "upcycl": "ukwenza into engcono ngezinto ezindala",
  "circular economy": "umnotho ozungezayo",
  "green economy": "umnotho ohlanzekile",
  "fair trade": "uhwebo olulungile",
  "ethical sourcing": "ukuthenga ngendlela efanele",
  "corporate social responsibility": "umthwalo wenkampani emphakathini",
  "esg": "imvelo, umphakathi, nokuphatha",
  "carbon neutral": "okungashiyi khabhoni",
  "net zero": "ukungashiyi gesi",
  "solar": "ngelanga",
  "wind energy": "amandla omoya",
  "hydroelectric": "amandla amanzi",
  "geothermal": "amandla okushisa komhlaba",
  "biomass": "izinto zempilo ezisetshenziswayo",
  "permaculture": "ukutshala okuqhubekayo",
  "organic": "okwemvelo",
  "agroforest": "ukutshala nokuhlala kwamahlathi",
  "aquaculture": "ukufuya izinhlanzi",
  "food securit": "ukuphepha kokudla",
  "water scarcit": "ukunqaba kwamanzi",

  // ═══════════════════════════════════════════════════════════════════════════
  // LEGAL & GOVERNANCE
  // ═══════════════════════════════════════════════════════════════════════════
  "constitution": "umthethosisekelo",
  "amendment": "ukuguqula umthetho",
  "legislat": "ukwenza umthetho",
  "statute": "umthetho",
  "ordinanc": "umthetho wendawo",
  "by-law": "umthetho wendawo",
  "jurisprudenc": "isayensi yomthetho",
  "precedent": "isibonelo somthetho",
  "plaintiff": "ummangali",
  "defendant": "ummangalelwa",
  "prosecut": "ukumangalela",
  "verdict": "isinqumo",
  "sentence": "isigwebo",
  "acquittal": "ukukhululwa",
  "appeal": "ukudlulisa icala",
  "jurisdiction": "indawo yomthetho",
  "subpoena": "incwadi yenkantolo",
  "affidavit": "isifungo esibhaliwe",
  "deposition": "ubufakazi obubhaliwe",
  "injunction": "umyalelo wenkantolo",
  "restraining order": "umyalelo wokuvimba",
  "due process": "indlela efanele yomthetho",
  "habeas corpus": "ilungelo lokukhululwa",
  "bail": "ibheyili",
  "parole": "ukukhululwa ngaphambi kwesikhathi",
  "probation": "isikhathi sokuhlolwa",
  "recidivis": "ukuphinda ukwenza icala",
  "rehabilitat": "ukusiza umuntu aphile kangcono",
  "restitut": "ukubuyisela",
  "reparation": "isinxephezelo",
  "sovereignty": "ukuzibusa",
  "governance": "ukuphatha",
  "transparency": "ukuba sobala",
  "corruption": "inkohlakalo",
  "nepotism": "ukuqasha izihlobo",
  "whistleblow": "ukuveza inkohlakalo",
  "ombudsman": "umxazululi wezinkinga",
  "tribunal": "inkantolo ekhethekile",
  "mediation": "ukuxazulula ngoxolo",

  // ═══════════════════════════════════════════════════════════════════════════
  // HEALTH & SOCIAL
  // ═══════════════════════════════════════════════════════════════════════════
  "pandemic": "isifo esisabalele emhlabeni",
  "epidemic": "isifo esisabalele",
  "endemic": "isifo sendawo",
  "quarantin": "ukuhlaliswa ngokwedwa",
  "vaccinat": "ukugoma",
  "immuniz": "ukuvikela isifo",
  "diagnos": "ukuhlonza isifo",
  "prognos": "ukukhombisa ikusasa lesifo",
  "therap": "ukwelapha",
  "rehabilit": "ukusiza umuntu aphile",
  "palliativ": "ukunciphisa ubuhlungu",
  "pharmaceut": "imithi",
  "generic": "imithi engenagama",
  "prescrip": "incwadi yomuthi",
  "dosage": "inani lomuthi",
  "side effect": "umthelela omubi",
  "chronic": "okungapheli",
  "acute": "okushesha",
  "symptom": "isibonakaliso",
  "syndrome": "iqoqo lezibonakaliso",
  "comorbid": "izifo eziningi ngasikhathi sinye",
  "malnutrit": "ukungondleki kahle",
  "sanitat": "inhlanzeko",
  "hygien": "inhlanzeko yomzimba",
  "maternal": "ngomama",
  "neonatal": "ngezingane ezisanda kuzalwa",
  "pediatric": "ngabantwana",
  "geriatric": "ngabantu abadala",
  "mental health": "impilo yengqondo",
  "wellbeing": "inhlalakahle",
  "occupational health": "impilo emsebenzini",
  "preventiv": "okuvimbayo",
  "holistic": "okuphelele",
  "indigenous": "okwendabuko",
  "traditional medicine": "umuthi wesintu",

  // ═══════════════════════════════════════════════════════════════════════════
  // COMMUNITY, SOCIETY & IMPACT
  // ═══════════════════════════════════════════════════════════════════════════
  "communit": "umphakathi",
  "civil societ": "umphakathi ojwayelekile",
  "non-profit": "inhlangano engenanzuzo",
  "ngo": "inhlangano engekho ngaphansi kukahulumeni",
  "philanthrop": "ukupha abanye",
  "voluntar": "ukuvolontiya",
  "activism": "ukusebenzela ushintsho",
  "advocacy": "ukumela abanye",
  "empowerment": "ukuhlonyiswa",
  "livelihood": "indlela yokuphila",
  "beneficiar": "ozuzayo",
  "initiat": "uhlelo olusha",
  "grassroots": "okusuka phansi",
  "participat": "ukubamba iqhaza",
  "inclusiv": "ukufaka wonke umuntu",
  "accessib": "ukutholakala",
  "marginali": "ukukhishwa inyumbazane",
  "vulnerable": "osengcupheni",
  "disadvantag": "ongenalutho",
  "indigenous": "okwendabuko",
  "heritage": "ifa",
  "cultural": "ngamasiko",
  "tradition": "isiko",
  "ancestral": "ngabokhokho",
  "customar": "okwejwayelekile",
  "patriarchal": "ukuphathwa amadoda",
  "matriarchal": "ukuphathwa abesifazane",
  "egalitarian": "okulinganayo",
  "equit": "ukulingana",
  "disparit": "ukungalingani",
  "inequalit": "ukungalingani",
  "poverty": "ububha",
  "deprivat": "ukuntuleka",
  "affluenc": "ingcebo",
  "prosperit": "ukuchuma",
  "upward mobilit": "ukukhula esigabeni",
  "social cohesion": "ukuhlangana komphakathi",
  "xenophob": "ukuzonda abokufika",
  "discriminat": "ubandlululo",
  "segregat": "ukuhlukanisa",
  "reconciliat": "ukubuyisana",
  "restorative justice": "ubulungisa obuvuselayo",
  "reparation": "isinxephezelo",
  "restitut": "ukubuyisela",
  "migration": "ukufuduka",
  "refugee": "umbaleki",
  "asylum": "indawo yokukhosela",
  "stateless": "ongenazwe",
  "citizenship": "ubuzwe",
  "naturalizat": "ukuba isakhamuzi",

  // ═══════════════════════════════════════════════════════════════════════════
  // AGRICULTURE & RURAL DEVELOPMENT
  // ═══════════════════════════════════════════════════════════════════════════
  "agriculture": "ezolimo",
  "agribusiness": "ibhizinisi lezolimo",
  "horticulture": "ukutshala izitshalo",
  "aquaculture": "ukufuya izinhlanzi",
  "livestock": "imfuyo",
  "poultry": "izinkukhu",
  "irrigation": "ukunisela",
  "fertili": "umanyolo",
  "pesticide": "umuthi wezinambuzane",
  "herbicide": "umuthi wokhula",
  "genetically modified": "okushintshwe ngesayensi",
  "harvest": "ukuvuna",
  "yield": "isivuno",
  "subsistence": "ukuziphilisa",
  "commercial farming": "ukulima ngokuthengisa",
  "cooperative": "inhlangano yabalimi",
  "land reform": "ukuguqulwa komhlaba",
  "tenure": "ilungelo lomhlaba",
  "title deed": "itayitela lomhlaba",
  "cadastral": "irejista yomhlaba",
  "communal land": "umhlaba womphakathi",
  "arable": "okungatshalwa",
  "fallow": "umhlaba ophumule",
  "crop rotation": "ukushintshana kwezitshalo",
  "monocultur": "ukutshala into eyodwa",
  "polycultur": "ukutshala izinto eziningi",
  "agro-processing": "ukusebenza kwezolimo",
  "value addition": "ukwandisa inani",
  "cold chain": "uhlelo lokugcina ukudla kubanda",
  "food processing": "ukusebenza kokudla",
  "food safety": "ukuphepha kokudla",
  "traceabilit": "ukulandelela umkhiqizo",

  // ═══════════════════════════════════════════════════════════════════════════
  // GENERAL DIFFICULT VOCABULARY
  // ═══════════════════════════════════════════════════════════════════════════
  "accomplish": "ukufeza",
  "acknowledg": "ukuvuma",
  "adequate": "okwanele",
  "advocat": "ukumela",
  "alleviat": "ukunciphisa",
  "ambigu": "okungaqondakali",
  "anticipat": "ukulindela",
  "appreciat": "ukwazisa",
  "approximat": "cishe",
  "arbitrary": "okungenasikhathi",
  "aspiration": "isifiso",
  "authentic": "okweqiniso",
  "autonomous": "okuzimele",
  "catastroph": "inhlekelele",
  "circumstan": "isimo",
  "coher": "okuqondakalayo",
  "commensurate": "okulinganayo",
  "comprehensive": "okuphelele",
  "compulsory": "okuphoqelekile",
  "concession": "ukuvuma",
  "confiscate": "ukuthatha",
  "congregat": "ukuhlangana",
  "conscious": "okuqondayo",
  "consequen": "umphumela",
  "consider": "ukucabanga",
  "constitut": "ukwakha",
  "contemporar": "okwamanje",
  "contradict": "ukuphikisana",
  "controver": "impikiswano",
  "conven": "okujwayelekile",
  "correlat": "ukuhlobana",
  "corresponden": "ukuxhumana",
  "credib": "okukholekayo",
  "culpab": "onesicelo",
  "cumulativ": "okuqoqekayo",
  "deficien": "ukuntuleka",
  "deliberat": "ngamabomu",
  "detrimental": "okuyingozi",
  "deviat": "ukuphambuka",
  "dilemma": "isimo esinzima",
  "diminish": "ukunciphisa",
  "discrepanc": "ukungafani",
  "disseminat": "ukusabalalisa",
  "distinguish": "ukuhlukanisa",
  "divers": "okuhlukahlukene",
  "dominan": "okunamandla",
  "efficien": "okusebenza kahle",
  "elimin": "ukususa",
  "elicit": "ukukhipha",
  "embark": "ukuqala",
  "encompass": "ukuhlanganisa",
  "endeavo": "ukuzama",
  "enhance": "ukwandisa",
  "enormous": "okukhulu kakhulu",
  "ensur": "ukuqinisekisa",
  "equip": "ukuhlomisa",
  "equivalent": "okulinganayo",
  "eradic": "ukuqeda nya",
  "essential": "okubalulekile",
  "establish": "ukusungula",
  "evident": "okubonakala",
  "exacerbat": "ukwenza kube kubi",
  "exceed": "ukudlula",
  "excerpt": "ingxenyana",
  "excessiv": "okwedlulele",
  "exclusiv": "okwekhethelo",
  "exemplar": "isibonelo esihle",
  "exempt": "okukhululiwe",
  "exhaust": "ukuqeda",
  "exorbitant": "okwedlulele kakhulu",
  "expedit": "ukusheshisa",
  "explicit": "okucacile",
  "exploit": "ukusebenzisa",
  "exponent": "ukukhulayo",
  "exquisit": "okuhle kakhulu",
  "extravagan": "ukuchitha kakhulu",
  "facilitator": "umxhasi",
  "fluctuat": "ukuguquguquka",
  "formidab": "okwesabekayo",
  "forthcoming": "okuzayo",
  "fractur": "ukuphuka",
  "fundament": "okuyisisekelo",
  "genuinene": "ukuba ngokoqobo",
  "gratuit": "okungakhokhisiwe",
  "guarantee": "isiqinisekiso",
  "harness": "ukusebenzisa",
  "hazard": "ingozi",
  "hindranc": "isithiyo",
  "hypothe": "umqondo ongaqinisekiswanga",
  "imminent": "okusondela",
  "impair": "ukuphazamisa",
  "impeccab": "okungenasici",
  "impediement": "isithiyo",
  "imperative": "okubalulekile kakhulu",
  "implicit": "okungashiwongo",
  "inaccessib": "okungatholakali",
  "inadequat": "okunganelea",
  "inaugurate": "ukuqala ngokusemthethweni",
  "incent": "isikhuthazi",
  "incidenc": "isehlakalo",
  "incorporat": "ukufaka",
  "increment": "okunyukayo",
  "indigenous": "okwendabuko",
  "indispensab": "okungagwemeki",
  "inequit": "ukungalingani",
  "inherent": "okufakiwe",
  "innate": "okwemvelo",
  "insufficien": "okunganelea",
  "intangib": "okungathintweki",
  "interdependent": "okuxhomeke komunye",
  "interim": "okwesikhashana",
  "intermittent": "okunganakho ukuqhubeka",
  "interven": "ukungenelela",
  "intrinsic": "okungaphakathi",
  "jeopardiz": "ukufaka engcupheni",
  "judicious": "okuhlakaniph",
  "juxtapos": "ukubeka ndawonye",
  "legitimate": "okungokomthetho",
  "lenien": "okumnene",
  "lucrat": "okuzuzisayo",
  "magnitud": "ubukhulu",
  "malfunction": "ukungasebenzi kahle",
  "mandator": "okuphoqelekile",
  "manifest": "ukubonakala",
  "meticulous": "okucophelele",
  "monopoliz": "ukubusa",
  "negligib": "okuncane kakhulu",
  "nonchalant": "onganandaba",
  "nondescript": "okungenalutho olukhethekile",
  "notoriou": "okudumile ngenxa yobubi",
  "novice": "umuntu omusha",
  "nuan": "umehluko omncane",
  "obligat": "ukuphoqeleka",
  "obscur": "okungaqondakali",
  "obsolet": "okungasasebenzi",
  "obstacl": "isithiyo",
  "omission": "ukuphuthelwa",
  "onerous": "okunzima",
  "ostensib": "ngokubonakala",
  "paradigm": "indlela yokucabanga",
  "paradox": "into ephikisanayo",
  "paramount": "okubaluleke kakhulu",
  "phenomenon": "isenzakalo",
  "plausib": "okungenzeka",
  "plight": "isimo esinzima",
  "pragmat": "okusebenzayo",
  "precarious": "okuyingozi",
  "precedent": "isibonelo sangaphambili",
  "prerequisit": "okudingekayo kuqala",
  "prevalent": "okuvamile",
  "proactive": "okwenza ngaphambi kwesikhathi",
  "profound": "okujulile",
  "prohibit": "ukuvimbela",
  "proliferat": "ukwanda",
  "prominent": "okuvelele",
  "propensit": "isifiso",
  "proportionat": "okulinganayo",
  "protagonis": "umlingiswa oyinhloko",
  "provisional": "okwesikhashana",
  "prudent": "okuhlakaniph",
  "quintessential": "okuyisibonelo esiphelele",
  "ramificat": "umphumela",
  "rationale": "isizathu",
  "recip": "ukubuyisana",
  "reconcil": "ukubuyisana",
  "redundan": "okungadingeki",
  "refurbish": "ukulungisa kabusha",
  "reinforce": "ukuqinisa",
  "relinquish": "ukuyeka",
  "remedy": "ikhambi",
  "reminiscen": "ukukhumbula",
  "repercussion": "umphumela omubi",
  "replenish": "ukugcwalisa kabusha",
  "reprehen": "okubi kakhulu",
  "reputable": "okunesithunzi",
  "requisite": "okudingekayo",
  "resolut": "ukuzimisela",
  "restrain": "ukubamba",
  "retrospect": "ukubheka emuva",
  "revitaliz": "ukuvuselela",
  "revolutioniz": "ukuguqula",
  "rigorous": "okuqinile",
  "robust": "okuqinile",
  "rudimentar": "okuyisisekelo",
  "scrutin": "ukuhlola",
  "significan": "okubalulekile",
  "simultaneous": "ngasikhathi sinye",
  "sophisticat": "okuthuthukile",
  "spontaneous": "okwenzeka ngokuzenzakalelayo",
  "stagnant": "okungakhuli",
  "stipulat": "ukubekela imibandela",
  "subordinat": "ongaphansi",
  "substantia": "okukhulu",
  "superficial": "okungaphandle",
  "supplement": "okwenezelayo",
  "surplus": "okwedlulile",
  "susceptib": "okusengcupheni",
  "tentat": "okungaqinisekiswanga",
  "thorough": "okuphelele",
  "threshold": "umngcele",
  "transform": "ukushintsha",
  "transition": "ukushintsha",
  "transparen": "okusobala",
  "turbulен": "okudidekile",
  "ubiquitous": "okutholakala yonke indawo",
  "unanim": "ngazwilinye",
  "undermin": "ukucekela phansi",
  "universal": "okwanele wonke umuntu",
  "unprecedented": "okungazange kwenzeke",
  "upheaval": "ukuguquka okukhulu",
  "utilis": "ukusebenzisa",
  "versatil": "okusebenza ngezindlela eziningi",
  "viab": "okusebenzayo",
  "vigorous": "okunamandla",
  "volatile": "okuguquguqukayo",
  "warrant": "isizathu",
  "wholesome": "okuhle",
  "yield": "ukukhiqiza",
  "zealous": "okukhuthele",
};

export default GLOSSARY;
